services:
  # Backend API Service
  - type: web
    name: oakland-ai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: oakland-ai-db
          property: connectionString

  # Frontend Service
  - type: web
    name: oakland-ai-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://oakland-ai-backend.onrender.com

databases:
  - name: oakland-ai-db
    databaseName: oaklandai
    user: oaklandai
    plan: free
